sort all edges based on timestamps  
collect edge-lists in delta-interval  
drop duplicates in each edge-list  
sort each based on end-points  
number of bidrirectional edges= df-old - df-new  

In [2]:
import pandas as pd
import numpy as np


In [16]:
graph = pd.read_csv('graph.txt', sep=' ')
print(graph)

   out_node  in_node  timestamp
0         0        2          2
1         1        0          2
2         0        1          4
3         1        2          4
4         0        2          4
5         1        3          3


In [63]:
graph_sorted_time = graph.sort_values(by= ['timestamp'])
graph_sorted_time = graph_sorted_time.reset_index(drop=True)
print(graph_sorted_time)
df = pd.DataFrame(dtype=np.int32)
print(graph_sorted_time.loc[5])
df.append(graph_sorted_time.loc[2])
print(df)
gst_np = graph_sorted_time.to_numpy()
print(gst_np)
timestamps = gst_np[:,2]
# timestamps

   out_node  in_node  timestamp
0         0        2          2
1         1        0          2
2         1        3          3
3         0        1          4
4         1        2          4
5         0        2          4
out_node     0
in_node      2
timestamp    4
Name: 5, dtype: int64
Empty DataFrame
Columns: []
Index: []
[[0 2 2]
 [1 0 2]
 [1 3 3]
 [0 1 4]
 [1 2 4]
 [0 2 4]]


In [62]:
delta = 2

start_time_index = 0
end_time_index = 1
col = []
while start_time_index < timestamps.size-1:
    col_row = [graph_sorted_time.iloc[start_time_index]]
    
    while end_time_index < timestamps.size and timestamps[end_time_index] < timestamps[start_time_index] + delta:
        col_row.append(graph_sorted_time.iloc[end_time_index])
        end_time_index += 1
        #print(start_time_index, end_time_index)
    if len(col_row) > 1:
        #print(col_row)
        df = pd.concat(col_row, axis=1).transpose()
        print(df)
        col.append(df)
    if end_time_index != timestamps.size:
        start_time_index += 1
        if(end_time_index <= start_time_index):
            end_time_index = start_time_index + 1
    else: break
        





#edge_list_collection = collectInDelta(delta)

   out_node  in_node  timestamp
0         0        2          2
1         1        0          2
2         1        3          3
   out_node  in_node  timestamp
2         1        3          3
3         0        1          4
4         1        2          4
5         0        2          4


In [57]:
for delta_df in col:
    count_orig = delta_df.count()
    delta_df delta_df.drop_duplicates(['out_node', 'in_node'])
    

out_node  in_node  timestamp
0         0        2          2
1         1        0          2
2         1        3          3